{{- if .Values.enabled }}
{{- if or .Values.worker_agent.envSecret .Values.global.envSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "worker_agent") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "worker_agent")) | nindent 4 }}
data:
  {{- if .Values.global.envSecret -}}
  {{- include "helper.secret" (dict "root" . "data" .Values.global.envSecret) | indent 2 }}
  {{- end -}}
  {{- if .Values.worker_agent.envSecret -}}
  {{- include "helper.secret" (dict "root" . "data" .Values.worker_agent.envSecret) | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end }}
