{{- if .Values.enabled }}
{{- if eq .Values.worker_document.deploymentType "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "worker_document") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "worker_document")) | nindent 4 }}
spec:
  {{- if not .Values.worker_document.autoscaling.enabled }}
  replicas: {{ .Values.worker_document.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.worker_document.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "worker_document") | nindent 6 }}
  strategy:
    type: {{ .Values.worker_document.strategy.type }}
    {{- if eq .Values.worker_document.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.worker_document.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.worker_document.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    {{- include "helper.component.podTemplate" (dict "root" . "name" "worker_document" "component" .Values.worker_document) | nindent 4 }}
{{- end }}
{{- end }}
