{{- if and .Values.enabled .Values.worker_async_api.enabled }}
{{- if eq .Values.worker_async_api.deploymentType "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "worker_async_api") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "worker_async_api")) | nindent 4 }}
spec:
  {{- if not .Values.worker_async_api.autoscaling.enabled }}
  replicas: {{ .Values.worker_async_api.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.worker_async_api.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "worker_async_api") | nindent 6 }}
  strategy:
    type: {{ .Values.worker_async_api.strategy.type }}
    {{- if eq .Values.worker_async_api.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.worker_async_api.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.worker_async_api.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    {{- include "helper.component.podTemplate" (dict "root" . "name" "worker_async_api" "component" .Values.worker_async_api) | nindent 4 }}
{{- end }}
{{- end }}
