"""reports (bug/idea/question) with admin triage

Revision ID: 6b724f3d02fa
Revises: fc20e773c29f
Create Date: 2026-09-23 17:11:38.805268

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b724f3d02fa"
down_revision: str | None = "fc20e773c29f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("user_display", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("BUG", "IDEA", "QUESTION", name="report_type"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("NEW", "IN_PROGRESS", "RESOLVED", "WONT_FIX", name="report_status"), nullable=False
        ),
        sa.Column("screenshot_key", sa.String(), nullable=True),
        sa.Column("admin_response", sa.Text(), nullable=True),
        sa.Column("responded_by", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_user_id"), "reports", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_user_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
