"""ephemeral analysis and dossier association tables

Revision ID: 7f1e8bb1c9da
Revises: d4e5f6a7b8c9
Create Date: 2026-09-24 10:17:39.603785

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f1e8bb1c9da"
down_revision: str | None = "d4e5f6a7b8c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyse_ephemeres",
        sa.Column("analyse_id", sa.UUID(), nullable=False),
        sa.Column("persist", sa.Boolean(), nullable=False),
        sa.Column("last_run_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analyse_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("analyse_id"),
    )
    op.create_index(op.f("ix_analyse_ephemeres_expires_at"), "analyse_ephemeres", ["expires_at"], unique=False)
    op.create_table(
        "dossier_ephemeres",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("analyse_ephemere_id", sa.UUID(), nullable=True),
        sa.Column("persist", sa.Boolean(), nullable=False),
        sa.Column("ttl_hours", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analyse_ephemere_id"], ["analyse_ephemeres.analyse_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dossier_id"], ["dossiers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("dossier_id"),
    )
    op.create_index(op.f("ix_dossier_ephemeres_expires_at"), "dossier_ephemeres", ["expires_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dossier_ephemeres_expires_at"), table_name="dossier_ephemeres")
    op.drop_table("dossier_ephemeres")
    op.drop_index(op.f("ix_analyse_ephemeres_expires_at"), table_name="analyse_ephemeres")
    op.drop_table("analyse_ephemeres")
    # ### end Alembic commands ###
