"""add created_by to analyse_ephemere

Revision ID: 6b349e53d77a
Revises: 7f1e8bb1c9da
Create Date: 2026-09-24 10:58:56.450499

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b349e53d77a"
down_revision: str | None = "7f1e8bb1c9da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analyse_ephemeres", sa.Column("created_by", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyse_ephemeres", "created_by")
    # ### end Alembic commands ###
