"""add created_by to dossier_ephemere

Revision ID: 2b084dba1bc8
Revises: 6b349e53d77a
Create Date: 2026-09-24 11:12:49.083960

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b084dba1bc8"
down_revision: str | None = "6b349e53d77a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dossier_ephemeres", sa.Column("created_by", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dossier_ephemeres", "created_by")
    # ### end Alembic commands ###
