"""execution logs, document pages and predictions, message sources, analyse shares

Revision ID: e64f2799cc05
Revises: 42c763907a77
Create Date: 2026-09-22 22:57:02.524232

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e64f2799cc05"
down_revision: str | None = "42c763907a77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyse_shares",
        sa.Column("analyse_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("EMAIL", "KEYCLOAK_GROUP", name="analyse_share_kind"), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("token_hash", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("keycloak_group", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analyse_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analyse_shares_analyse_id"), "analyse_shares", ["analyse_id"], unique=False)
    op.create_index(op.f("ix_analyse_shares_token_hash"), "analyse_shares", ["token_hash"], unique=False)
    op.create_table(
        "document_pages",
        sa.Column("dossier_document_id", sa.UUID(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("x_min", sa.Float(), nullable=True),
        sa.Column("y_min", sa.Float(), nullable=True),
        sa.Column("x_max", sa.Float(), nullable=True),
        sa.Column("y_max", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["dossier_document_id"], ["dossier_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_pages_dossier_document_id"), "document_pages", ["dossier_document_id"], unique=False
    )
    op.create_table(
        "execution_logs",
        sa.Column("execution_step_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.Enum("DEBUG", "INFO", "WARNING", "ERROR", name="execution_log_level"), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["execution_step_id"], ["execution_steps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_execution_logs_execution_step_id"), "execution_logs", ["execution_step_id"], unique=False)
    op.create_table(
        "document_predictions",
        sa.Column("document_page_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("LABEL", "ENTITY", name="prediction_kind"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("x_min", sa.Float(), nullable=True),
        sa.Column("y_min", sa.Float(), nullable=True),
        sa.Column("x_max", sa.Float(), nullable=True),
        sa.Column("y_max", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_page_id"], ["document_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_predictions_document_page_id"), "document_predictions", ["document_page_id"], unique=False
    )
    op.create_table(
        "message_sources",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("dossier_document_id", sa.UUID(), nullable=True),
        sa.Column("execution_step_id", sa.UUID(), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["dossier_document_id"], ["dossier_documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["execution_step_id"], ["execution_steps.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_sources_message_id"), "message_sources", ["message_id"], unique=False)
    op.create_table(
        "prediction_validations",
        sa.Column("prediction_id", sa.UUID(), nullable=False),
        sa.Column("validator_user_id", sa.String(), nullable=False),
        sa.Column(
            "status", sa.Enum("VALIDATED", "CORRECTED", "REJECTED", name="prediction_validation_status"), nullable=False
        ),
        sa.Column("corrected_value", sa.Text(), nullable=True),
        sa.Column("x_min", sa.Float(), nullable=True),
        sa.Column("y_min", sa.Float(), nullable=True),
        sa.Column("x_max", sa.Float(), nullable=True),
        sa.Column("y_max", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["prediction_id"], ["document_predictions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prediction_validations_prediction_id"), "prediction_validations", ["prediction_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prediction_validations_prediction_id"), table_name="prediction_validations")
    op.drop_table("prediction_validations")
    op.drop_index(op.f("ix_message_sources_message_id"), table_name="message_sources")
    op.drop_table("message_sources")
    op.drop_index(op.f("ix_document_predictions_document_page_id"), table_name="document_predictions")
    op.drop_table("document_predictions")
    op.drop_index(op.f("ix_execution_logs_execution_step_id"), table_name="execution_logs")
    op.drop_table("execution_logs")
    op.drop_index(op.f("ix_document_pages_dossier_document_id"), table_name="document_pages")
    op.drop_table("document_pages")
    op.drop_index(op.f("ix_analyse_shares_token_hash"), table_name="analyse_shares")
    op.drop_index(op.f("ix_analyse_shares_analyse_id"), table_name="analyse_shares")
    op.drop_table("analyse_shares")
    # ### end Alembic commands ###
