"""bounding boxes as their own table

Revision ID: 0464cba98183
Revises: e64f2799cc05
Create Date: 2026-09-23 08:34:25.688394

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0464cba98183"
down_revision: str | None = "e64f2799cc05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bounding_boxes",
        sa.Column("document_page_id", sa.UUID(), nullable=False),
        sa.Column("x_min", sa.Float(), nullable=False),
        sa.Column("y_min", sa.Float(), nullable=False),
        sa.Column("x_max", sa.Float(), nullable=False),
        sa.Column("y_max", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_page_id"], ["document_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bounding_boxes_document_page_id"), "bounding_boxes", ["document_page_id"], unique=False)
    op.drop_column("document_pages", "y_min")
    op.drop_column("document_pages", "y_max")
    op.drop_column("document_pages", "x_min")
    op.drop_column("document_pages", "x_max")
    op.add_column("document_predictions", sa.Column("bounding_box_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_document_predictions_bounding_box_id",
        "document_predictions",
        "bounding_boxes",
        ["bounding_box_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("document_predictions", "y_min")
    op.drop_column("document_predictions", "y_max")
    op.drop_column("document_predictions", "x_min")
    op.drop_column("document_predictions", "x_max")
    op.add_column("prediction_validations", sa.Column("bounding_box_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_prediction_validations_bounding_box_id",
        "prediction_validations",
        "bounding_boxes",
        ["bounding_box_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("prediction_validations", "y_min")
    op.drop_column("prediction_validations", "y_max")
    op.drop_column("prediction_validations", "x_min")
    op.drop_column("prediction_validations", "x_max")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prediction_validations",
        sa.Column("x_max", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prediction_validations",
        sa.Column("x_min", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prediction_validations",
        sa.Column("y_max", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prediction_validations",
        sa.Column("y_min", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.drop_constraint("fk_prediction_validations_bounding_box_id", "prediction_validations", type_="foreignkey")
    op.drop_column("prediction_validations", "bounding_box_id")
    op.add_column(
        "document_predictions",
        sa.Column("x_max", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_predictions",
        sa.Column("x_min", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_predictions",
        sa.Column("y_max", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "document_predictions",
        sa.Column("y_min", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.drop_constraint("fk_document_predictions_bounding_box_id", "document_predictions", type_="foreignkey")
    op.drop_column("document_predictions", "bounding_box_id")
    op.add_column(
        "document_pages", sa.Column("x_max", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "document_pages", sa.Column("x_min", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "document_pages", sa.Column("y_max", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column(
        "document_pages", sa.Column("y_min", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_bounding_boxes_document_page_id"), table_name="bounding_boxes")
    op.drop_table("bounding_boxes")
    # ### end Alembic commands ###
