"""add agent_conversations, agent_messages, agent_message_sources, agent_chat_events

Revision ID: d44d56718aa9
Revises: 2b084dba1bc8
Create Date: 2026-09-25 08:49:21.697939

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d44d56718aa9"
down_revision: str | None = "2b084dba1bc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_conversations",
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_conversations_created_by"), "agent_conversations", ["created_by"], unique=False)
    op.create_table(
        "agent_chat_events",
        sa.Column("agent_conversation_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("TOOL_CALL", "TOOL_RESULT", "THINKING", "DONE", "ERROR", name="agent_chat_event_kind"),
            nullable=False,
        ),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["agent_conversation_id"], ["agent_conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_chat_events_agent_conversation_id"), "agent_chat_events", ["agent_conversation_id"], unique=False
    )
    op.create_table(
        "agent_messages",
        sa.Column("agent_conversation_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", "TOOL_CALL", "TOOL_RESULT", "ERROR", name="agent_message_role"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("tool_name", sa.String(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["agent_conversation_id"], ["agent_conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_messages_agent_conversation_id"), "agent_messages", ["agent_conversation_id"], unique=False
    )
    op.create_table(
        "agent_message_sources",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=True),
        sa.Column("analyse_id", sa.UUID(), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analyse_id"], ["analyses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dossier_id"], ["dossiers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["message_id"], ["agent_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_message_sources_message_id"), "agent_message_sources", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_message_sources_message_id"), table_name="agent_message_sources")
    op.drop_table("agent_message_sources")
    op.drop_index(op.f("ix_agent_messages_agent_conversation_id"), table_name="agent_messages")
    op.drop_table("agent_messages")
    sa.Enum(name="agent_message_role").drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f("ix_agent_chat_events_agent_conversation_id"), table_name="agent_chat_events")
    op.drop_table("agent_chat_events")
    sa.Enum(name="agent_chat_event_kind").drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f("ix_agent_conversations_created_by"), table_name="agent_conversations")
    op.drop_table("agent_conversations")
    # ### end Alembic commands ###
