"""message feedback (thumbs up/down, reasons, comment)

Revision ID: fc20e773c29f
Revises: 572981f30ad1
Create Date: 2026-09-23 17:00:39.839442

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc20e773c29f"
down_revision: str | None = "572981f30ad1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedbacks",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("value", sa.Enum("UP", "DOWN", name="feedback_value"), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", "user_id", name="uq_feedbacks_message_id_user_id"),
    )
    op.create_index(op.f("ix_feedbacks_message_id"), "feedbacks", ["message_id"], unique=False)
    op.create_index(op.f("ix_feedbacks_user_id"), "feedbacks", ["user_id"], unique=False)
    op.create_table(
        "feedback_reasons",
        sa.Column("feedback_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "INCORRECT_ANSWER",
                "NOT_USEFUL",
                "QUESTIONABLE_SOURCES",
                "INAPPROPRIATE_TONE",
                "OTHER",
                name="feedback_reason_code",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["feedback_id"], ["feedbacks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("feedback_id", "reason"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback_reasons")
    op.drop_index(op.f("ix_feedbacks_user_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_message_id"), table_name="feedbacks")
    op.drop_table("feedbacks")
    # ### end Alembic commands ###
