"""initial schema

Revision ID: 80d46debbe61
Revises:
Create Date: 2026-09-22 22:07:43.728091

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80d46debbe61"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyses",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("classification_prompt", sa.Text(), nullable=False),
        sa.Column("extraction_prompt", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agents",
        sa.Column("analyse_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analyse_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_analyse_id"), "agents", ["analyse_id"], unique=False)
    op.create_table(
        "dossiers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("analyse_id", sa.UUID(), nullable=False),
        sa.Column("analyse_version", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("EN_ATTENTE", "EN_COURS", "TERMINE", "ARRETE", "ECHEC", name="dossier_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analyse_id"], ["analyses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dossiers_analyse_id"), "dossiers", ["analyse_id"], unique=False)
    op.create_table(
        "entity_definitions",
        sa.Column("analyse_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column(
            "type", sa.Enum("TEXTE", "DATE", "NOMBRE", "BOOLEEN", "IDENTIFIANT", name="entity_type"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analyse_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entity_definitions_analyse_id"), "entity_definitions", ["analyse_id"], unique=False)
    op.create_table(
        "label_definitions",
        sa.Column("analyse_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analyse_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_label_definitions_analyse_id"), "label_definitions", ["analyse_id"], unique=False)
    op.create_table(
        "dossier_documents",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["dossier_id"], ["dossiers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dossier_documents_dossier_id"), "dossier_documents", ["dossier_id"], unique=False)
    op.create_table(
        "execution_steps",
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("CLASSIFICATION", "EXTRACTION", "AGENT", name="execution_step_kind"), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("status", sa.Enum("EN_COURS", "TERMINE", "ECHEC", name="execution_step_status"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["dossier_id"], ["dossiers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_execution_steps_dossier_id"), "execution_steps", ["dossier_id"], unique=False)
    op.create_table(
        "field_versions",
        sa.Column("analyse_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column(
            "field",
            sa.Enum(
                "CLASSIFICATION_PROMPT",
                "CLASSIFICATION_LABELS",
                "EXTRACTION_PROMPT",
                "EXTRACTION_ENTITIES",
                "AGENT_PROMPT",
                "AGENT_TOOLS",
                "AGENT_OUTPUT",
                name="versioned_field",
            ),
            nullable=False,
        ),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["analyse_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_field_versions_agent_id"), "field_versions", ["agent_id"], unique=False)
    op.create_index(op.f("ix_field_versions_analyse_id"), "field_versions", ["analyse_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_field_versions_analyse_id"), table_name="field_versions")
    op.drop_index(op.f("ix_field_versions_agent_id"), table_name="field_versions")
    op.drop_table("field_versions")
    op.drop_index(op.f("ix_execution_steps_dossier_id"), table_name="execution_steps")
    op.drop_table("execution_steps")
    op.drop_index(op.f("ix_dossier_documents_dossier_id"), table_name="dossier_documents")
    op.drop_table("dossier_documents")
    op.drop_index(op.f("ix_label_definitions_analyse_id"), table_name="label_definitions")
    op.drop_table("label_definitions")
    op.drop_index(op.f("ix_entity_definitions_analyse_id"), table_name="entity_definitions")
    op.drop_table("entity_definitions")
    op.drop_index(op.f("ix_dossiers_analyse_id"), table_name="dossiers")
    op.drop_table("dossiers")
    op.drop_index(op.f("ix_agents_analyse_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("analyses")
    # ### end Alembic commands ###
