"""screenshot key on document pages

Revision ID: f3ace41df805
Revises: c624935c6b31
Create Date: 2026-09-23 09:49:31.840567

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3ace41df805"
down_revision: str | None = "c624935c6b31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_pages", sa.Column("screenshot_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_pages", "screenshot_key")
    # ### end Alembic commands ###
