{{- if and .Values.enabled .Values.worker_async_api.enabled }}
{{- if or .Values.worker_async_api.envSecret .Values.global.envSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "worker_async_api") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "worker_async_api")) | nindent 4 }}
data:
  {{- if .Values.global.envSecret -}}
  {{- include "helper.secret" (dict "root" . "data" .Values.global.envSecret) | indent 2 }}
  {{- end -}}
  {{- if .Values.worker_async_api.envSecret -}}
  {{- include "helper.secret" (dict "root" . "data" .Values.worker_async_api.envSecret) | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end }}
