{{- if and .Values.enabled .Values.worker_async_api.enabled }}
{{- if eq .Values.worker_async_api.deploymentType "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "worker_async_api") }}
  labels: {{- include "helper.labels" (dict "root" . "componentName" "worker_async_api") | nindent 4 }}
spec:
  {{- if not .Values.worker_async_api.autoscaling.enabled }}
  replicas: {{ .Values.worker_async_api.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.worker_async_api.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "worker_async_api") | nindent 6 }}
  serviceName: {{ include "helper.componentFullname" (dict "root" . "componentName" "worker_async_api") }}
  {{- with .Values.worker_async_api.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "helper.component.podTemplate" (dict "root" . "name" "worker_async_api" "component" .Values.worker_async_api) | nindent 4 }}
  {{- if or .Values.worker_async_api.volumeClaims .Values.worker_async_api.extraVolumeClaims }}
  volumeClaimTemplates: {{- toYaml (concat (default (list) .Values.worker_async_api.volumeClaims) (default (list) .Values.worker_async_api.extraVolumeClaims)) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
