{{- if .Values.enabled }}
{{- if and .Values.worker_render.serviceAccount.enabled .Values.worker_render.serviceAccount.role.create .Values.worker_render.serviceAccount.role.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "worker_render") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "worker_render")) | nindent 4 }}
rules: {{- toYaml .Values.worker_render.serviceAccount.role.rules | nindent 0 }}
{{- end }}
{{- end }}
